export const Rankings: PlayerStatsCardProps[] = [
  {
    id: 1,
    name: "Player 1",
    nickname: "Ace",
    gross: 83,
    hcp: 15,
    net: 68,
    points: 36,
    gender: "Men",
  },
  {
    id: 2,
    name: "Player 2",
    nickname: "Birdie",
    gross: 82,
    hcp: 12,
    net: 70,
    points: 34,
    gender: "Ladies",
  },
  {
    id: 3,
    name: "Player 3",
    nickname: "Eagle",
    gross: 75,
    hcp: 10,
    net: 65,
    points: 38,
    gender: "Men",
  },
  {
    id: 4,
    name: "Player 4",
    nickname: "Fairway",
    gross: 90,
    hcp: 18,
    net: 72,
    points: 33,
    gender: "Ladies",
  },
  {
    id: 5,
    name: "Player 5",
    nickname: "Chip",
    gross: 75,
    hcp: 9,
    net: 66,
    points: 37,
    gender: "Men",
  },
  {
    id: 6,
    name: "Player 6",
    nickname: "Putter",
    gross: 94,
    hcp: 20,
    net: 74,
    points: 31,
    gender: "Ladies",
  },
  {
    id: 7,
    name: "Player 7",
    nickname: "Drive",
    gross: 78,
    hcp: 11,
    net: 67,
    points: 35,
    gender: "Men",
  },
  {
    id: 8,
    name: "Player 8",
    nickname: "Slice",
    gross: 83,
    hcp: 14,
    net: 69,
    points: 36,
    gender: "Ladies",
  },
  {
    id: 9,
    name: "Player 9",
    nickname: "Hook",
    gross: 81,
    hcp: 13,
    net: 68,
    points: 37,
    gender: "Men",
  },
  {
    id: 10,
    name: "Player 10",
    nickname: "Lag",
    gross: 88,
    hcp: 17,
    net: 71,
    points: 32,
    gender: "Ladies",
  },
];

export const Events = [
  { id: "1", series: "2024-2025", seriesName: "Al Ain Par 3 Series" },
  { id: "2", series: "2024-2025", seriesName: "Al Ain Par 3 Series" },
  { id: "3", series: "2025-2026", seriesName: "Al Ain Par 3 Series" },
  { id: "4", series: "2025-2026", seriesName: "Al Ain Par 3 Series" },
  { id: "5", series: "2026-2027", seriesName: "Al Ain Par 3 Series" },
  { id: "6", series: "2026-2027", seriesName: "Al Ain Par 3 Series" },
];

export const Players = [
  {
    name: "Schalk S",
    email: "schalk@example.com",
    gender: "Male",
    handicap: 10,
    nickname: "Schalk",
    joinedAt: "2025-05-05",
    roundsPlayed: ["round1"],
    phoneNumber: "",
    membershipType: "",
    photoUrl: "",
  },
  {
    name: "Jesse",
    email: "jesse@example.com",
    gender: "Male",
    handicap: 7,
    nickname: "Schalk",
    joinedAt: "2025-05-05",
    roundsPlayed: ["round1"],
    phoneNumber: "",
    membershipType: "",
    photoUrl: "",
  },
  {
    name: "Fred",
    email: "fred@example.com",
    gender: "Male",
    handicap: 10,
    nickname: "Schalk",
    joinedAt: "2025-05-05",
    roundsPlayed: ["round1"],
    phoneNumber: "",
    membershipType: "",
    photoUrl: "",
  },
  {
    name: "Rob D",
    email: "rob.d@example.com",
    gender: "Male",
    handicap: 11,
    nickname: "Schalk",
    joinedAt: "2025-05-05",
    roundsPlayed: ["round1"],
    phoneNumber: "",
    membershipType: "",
    photoUrl: "",
  },
  {
    name: "Greg",
    email: "greg@example.com",
    gender: "Male",
    handicap: 5,
    nickname: "Schalk",
    joinedAt: "2025-05-05",
    roundsPlayed: ["round1"],
    phoneNumber: "",
    membershipType: "",
    photoUrl: "",
  },
  {
    name: "Kevin",
    email: "kevin@example.com",
    gender: "Male",
    handicap: 13,
    nickname: "Schalk",
    joinedAt: "2025-05-05",
    roundsPlayed: ["round1"],
    phoneNumber: "",
    membershipType: "",
    photoUrl: "",
  },
  {
    name: "Lee Anne",
    email: "leeanne@example.com",
    gender: "Female",
    handicap: 17,
    nickname: "Schalk",
    joinedAt: "2025-05-05",
    roundsPlayed: ["round1"],
    phoneNumber: "",
    membershipType: "",
    photoUrl: "",
  },
  {
    name: "Louise",
    email: "louise@example.com",
    gender: "Female",
    handicap: 14,
    nickname: "Schalk",
    joinedAt: "2025-05-05",
    roundsPlayed: ["round1"],
    phoneNumber: "",
    membershipType: "",
    photoUrl: "",
  },
  {
    name: "Zirkia",
    email: "zirkia@example.com",
    gender: "Female",
    handicap: 15,
    nickname: "Schalk",
    joinedAt: "2025-05-05",
    roundsPlayed: ["round1"],
    phoneNumber: "",
    membershipType: "",
    photoUrl: "",
  },
  {
    name: "Adel",
    email: "adel@example.com",
    gender: "Female",
    handicap: 16,
    nickname: "Schalk",
    joinedAt: "2025-05-05",
    roundsPlayed: ["round1"],
    phoneNumber: "",
    membershipType: "",
    photoUrl: "",
  },
];
